### ISSUE TITLE
Restarting LCD without a power down

### ISSUE THREAD

**Issue by Sargent0** [highfield/LcdHD44780Demo#1]
Scenario:
Start project in Visual Studio.  Stop project in Visual Studio.  Start project again in Visual Studio.
The screen doesn't 'update'.

POSSIBLE Reason:  
I think it is because the LCD never loses power.  Has to do with setting the LCD from 8bit to 4bit.  https://www.microchip.com/forums/FindPost/417907
_[**If the LCD gets powered down *like a device shut off* - this isn't a problem**]_

Fix:
Makes sure the LCD is in 8bit mode before switching to 4bit.
Use the warm-reset algorithm when starting the LCD (solution in [comment below](https://github.com/highfield/LcdHD44780Demo/issues/1#issuecomment-432097471))

**Comment by Sargent0** [comment]
(better solution below)

**Comment by highfield** [comment]
Oh, wow! nice catch indeed...
It's a while that I don't play with such hardware, but maybe you could help me. Did you try the warm-reset algorithm as described in Wikipedia (section "Mode Selection")?
https://en.wikipedia.org/wiki/Hitachi_HD44780_LCD_controller

**Comment by Sargent0** [comment]
Thanks for the help and sharing your work on the driver!
Performing the warm-reset algorithm works like a charm.
(Makes sure the LCD is in 8bit mode before switching to 4bit)

Here is the algorithm added to the StartAsync method.
```
      // Replace the code right above Mario's comment "//at this point the HD44780 is working in 4-bit mode"        
               this._bufferIndex = 0;
                for (int i = 0; i < 3; i++)
                {
                    this.WriteByte(0b0011);
                    this.Send();
                    await Task.Delay(6);    //this yields a small pause
                }
                this.WriteCommand(LcdSetFunc8);
                this.WriteCommand(LcdSetFunc4);
````

**Comment by highfield** [comment]
Thank you!
